export const greetingHome = "This is the Home page. Yo!";

import place from "../assets/imgs/place.png";
import cakes from "../assets/imgs/cakes.png";
import diamondGIF from "../assets/imgs/diamond1.gif";

export function createHome() {
const containerHome = document.createElement("div");
containerHome.classList.add("home-container");
const heading = document.createElement("h1");
heading.classList.add("home-title");
heading.textContent = "Welcome to Lilly's Sweet Treats!";
const cakeCard = document.createElement("div");
cakeCard.classList.add("home-card", "home-cake-card");
const cakeImg = document.createElement("img");
cakeImg.classList.add("home-image", "home-cake-image");
cakeImg.src = cakes;
const cakeInfo = document.createElement("div");
cakeInfo.classList.add("home-cake-info");
const cakeTitle = document.createElement("h2");
cakeTitle.classList.add("home-cake-title");
cakeTitle.textContent = "Best cakes this side of Venus!";
const cakeText = document.createElement("p");
cakeText.classList.add("home-cake-text");
cakeText.textContent = "Are you looking for high-quality, human-designed cakes? Tired of the same old industrial mixes that always leave that weird aftertaste? Well, look no further, friend.";
const cakeText2 = document.createElement("p");
cakeText2.classList.add("home-cake-text");
cakeText2.innerHTML = "<span class=\"lillys\">Lilly's Sweet Treats</span> boasts a selection of award-winning cakes made by an actual human being! From mild-tasting delicate cakes for folks with sensitive palates, to high-octane sugary powerhouses that will make your teeth shiver in sweet agony, we have it all!";
const cakeText3 = document.createElement("p");
cakeText3.classList.add("home-cake-text");
cakeText3.textContent = "Please take a look at our menu and choose from our highly curated list.";
cakeInfo.append(cakeTitle, cakeText, cakeText2, cakeText3);
cakeCard.append(cakeInfo, cakeImg);
const placeCard = document.createElement("div");
placeCard.classList.add("home-card", "home-place-card");
const placeImg = document.createElement("img");
placeImg.classList.add("home-image", "home-place-image");
placeImg.src = place;
const placeInfo = document.createElement("div");
placeInfo.classList.add("home-place-info");
const placeTitle = document.createElement("h2");
placeTitle.classList.add("home-place-title");
placeTitle.textContent = "Come visit us at our new location!";
const placeText = document.createElement("p");
placeText.classList.add("home-place-text");
placeText.innerHTML = "Ever since the <i>Big Accident</i> we have been on the lookout for a new place to continue with our mission of spreading the joy of sweetness to everyone. And now we have finally found it!";
const placeText2 = document.createElement("p");
placeText2.classList.add("home-place-text");
placeText2.innerHTML = "Situated on the outskirts of <i>Old Human Town</i>, our restaurant is easy to access via the Broken Boulevard or by riding the OHT metro to the last stop on the East. Please consult your personal AI for more information.";
const placeText3 = document.createElement("p");
placeText3.classList.add("home-place-text");
placeText3.textContent = "We are looking forward to welcoming you to our human-friendly restaurant! Just don't forget to wash your hands before coming.";
placeInfo.append(placeTitle, placeText, placeText2, placeText3);
placeCard.append(placeImg, placeInfo);
const bottomCard = document.createElement("div");
bottomCard.classList.add("home-card", "home-bottom-card");
const bottomImg = document.createElement("img");
bottomImg.classList.add("home-bottom-image");
bottomImg.src = diamondGIF;
const bottomImg2 = document.createElement("img");
bottomImg2.classList.add("home-bottom-image");
bottomImg2.src = diamondGIF;
const bottomImg3 = document.createElement("img");
bottomImg3.classList.add("home-bottom-image");
bottomImg3.src = diamondGIF;
const bottomImages = document.createElement("div");
bottomImages.classList.add("home-bottom-images");
bottomImages.append(bottomImg, bottomImg2, bottomImg3);
const bottomInfo = document.createElement("p");
bottomInfo.classList.add("home-bottom-info");
bottomInfo.innerHTML = "<span class=\"lillys\">Lilly's Sweet Treats</span> is a proud winner of the <i>2047, 2048 & 2049 Diamond of Awesomeness</i>.";
bottomCard.append(bottomImages, bottomInfo);
containerHome.append(heading, cakeCard, placeCard, bottomCard);

return containerHome;
}